version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ecotrifarm
      - SECRET_KEY=your-secret-key-change-in-production
      - CORS_ORIGINS=["http://localhost:8000"]
      - ENVIRONMENT=production
    depends_on:
      - db
    volumes:
      - ./backend/.env:/app/.env

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ecotrifarm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: